### ISSUE TITLE
Problem with very long file name

### ISSUE THREAD

**Issue by TritoXid** [ahrasis/net2ftp_v1.1#1]
Hi, I downloaded repository with project net2ftp and I finding one issue. When I create or upload file with really long name, some buttons not see. You can see it on screen. I using default skin Shinra from repository. How I can solve this issue when I need using files with long name ? Thanks for answer.

![net2ftp](https://user-images.githubusercontent.com/24209493/33071300-47068924-cebb-11e7-9e7a-1c666f40d77b.png)

**Comment by ahrasis** [comment]
What browser are you using? Is it updated to the latest version? I cannot replicate this on my FF or Chrome or Edge. I can alway see all three action buttons.

**Comment by ahrasis** [comment]
No response. Issue is closed
